# Custom Language File for Launcher Customizer

[ejs.app]
title = "MarcusK Studio Launcher"

[ejs.landing]
mediaGitHubURL = "https://marcusk.fun/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/marcusk"

[ejs.settings]
sourceGithubLink = "https://github.com/LeafdTK/Launcher"
supportLink = "https://github.com/LeafdTK/Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO MARCUSK EVENTS"
welcomeDescription = "The Goal Is Simple To Provide You With The Highest Quality Minecraft Videos And Events In The World!"
welcomeDescCTA = "You are just a few clicks away from the best event."
